### GET ALL PLAYERS

GET http://localhost:3000/

### GET PLAYER BY NUMBER

GET http://localhost:3000/11

### ADD PLAYER

POST http://localhost:3000/
Content-Type: application/json

{
    "name": "Harry Kane",
    "position": "striker",
    "number": 10,
    "nationality": "Brittish"
}

### DELETE ALL PLAYERS

DELETE http://localhost:3000/

### UPDATE PLAYER INFORMATION

PUT http://localhost:3000/11
Content-Type: application/json

{
    "name": "Harry Kane",
    "position": "striker",
    "number": 10,
    "nationality": "Brittish"
}