### GET ALL PLAYERS

GET http://localhost:3000/

###

GET http://localhost:3000/11

### POST PLAYER

POST http://localhost:3000/
Content-Type: application/json

{
    "name": "asdasd Kane",
    "position": "Forward",
    "number": 11,
    "nationality": "Brittish"
}

### DELETE ALL PLAYERS

DELETE http://localhost:3000/

###

PUT http://localhost:3000/11
Content-Type: application/json

{
    "name": "harry Kane",
    "position": "Forward",
    "number": 10,
    "nationality": "Brittish"
}