### GET ALL PLAYERS

GET http://localhost:3000/

### GET PLAYER BY NUMBER

GET http://localhost:3000/10

### ADD PLAYER

POST http://localhost:3000/
Content-Type: application/json

{
    "name": "Yves Bissouma",
    "position": "midfielder",
    "number": 38,
    "nationality": "Ivory Coast",
    "imageURL" : "https://cdne-totv8-prod.azureedge.net/media/fywh2h4j/firstteam_profiles_202223_yvesbissouma.png?anchor=center&mode=crop&quality=100&width=750"
}

### DELETE ALL PLAYERS

DELETE http://localhost:3000/

### UPDATE PLAYER INFORMATION

PUT http://localhost:3000/10
Content-Type: application/json

{
    "name": "Harry Kane",
    "position": "striker",
    "number": 55,
    "nationality": "Brittish"
}